services:
  kuriyr:
    build: .
    ports:
      - '4400:4400'
    volumes:
      - ./templates:/app/templates
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - KURIYR_FROM_NAME=My App
      - KURIYR_FROM_EMAIL=noreply@example.com
      - KURIYR_DEFAULT_LOCALE=en
      - KURIYR_PORT=4400
      - KURIYR_SMTP_HOST=smtp.example.com
      - KURIYR_SMTP_PORT=587
      - KURIYR_SMTP_SECURE=false
      # - KURIYR_SMTP_USER=your-user
      # - KURIYR_SMTP_PASS=your-password
      # - KURIYR_DASHBOARD_USER=admin
      # - KURIYR_DASHBOARD_PASSWORD=changeme
      # - KURIYR_API_TOKEN=your-secret-token
    restart: unless-stopped
